[versions]
androidGradlePlugin = "8.13.2"
kotlin = "2.3.0"
gradleVersionsPlugin = "0.53.0"
kotlinxCoroutines = "1.10.2"
dependencyGuard = "0.5.0"

androidxCore = "1.17.0"
androidxAppCompat = "1.7.1"
androidxActivity = "1.12.2"
androidxFragment = "1.8.9"
androidxBrowser = "1.9.0"
androidxWebkit = "1.15.0"
androidxPreference = "1.2.1"
androidxConstraintLayout = "2.2.1"
androidxCamera = "1.5.2"
mlkitBarcodeScanning = "17.3.0"
material = "1.13.0"
playReview = "2.0.2"
playAppUpdate = "2.1.0"
timber = "5.0.1"

ktlint = "1.8.0"

# for release

[libraries]
kotlinStdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlinxCoroutinesAndroid = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }

androidxCore = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidxAppCompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppCompat" }
androidxActivity = { group = "androidx.activity", name = "activity-ktx", version.ref = "androidxActivity" }
androidxFragment = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "androidxFragment" }
androidxBrowser = { group = "androidx.browser", name = "browser", version.ref = "androidxBrowser" }
androidxWebkit = { group = "androidx.webkit", name = "webkit", version.ref = "androidxWebkit" }
androidxPreference = { group = "androidx.preference", name = "preference-ktx", version.ref = "androidxPreference" }
androidxConstraintLayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidxConstraintLayout" }
androidxCameraView = { group = "androidx.camera", name = "camera-view", version.ref = "androidxCamera" }
androidxCameraCamera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "androidxCamera" }
androidxCameraLifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "androidxCamera" }
mlkitBarcodeScanning = { group = "com.google.mlkit", name = "barcode-scanning", version.ref = "mlkitBarcodeScanning" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
playReview = { group = "com.google.android.play", name = "review-ktx", version.ref = "playReview" }
playAppUpdate = { group = "com.google.android.play", name = "app-update-ktx", version.ref = "playAppUpdate" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }

ktlint = { group = "com.pinterest.ktlint", name = "ktlint-cli", version.ref = "ktlint" }

# for release

[plugins]
androidApplication = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinParcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
gradleVersions = { id = "com.github.ben-manes.versions", version.ref = "gradleVersionsPlugin" }
dependencyGuard = { id = "com.dropbox.dependency-guard", version.ref = "dependencyGuard" }

# for release

[bundles]
androidxCamera = [
    "androidxCameraView",
    "androidxCameraCamera2",
    "androidxCameraLifecycle"
]

# for release
